const districts = [
	"Honolulu",
	"Central",
	"Leeward",
	"Windward",
	"Hawaii",
	"Maui",
	"Kauai"
];

const complexAreas = [
	"Farrington-Kaiser-Kalani",
	"Kaimuki-McKinley-Roosevelt",
	"Aiea-Moanalua-Radford",
	"Leilehua-Mililani-Waialua",
	"Campbell-Kapolei",
	"Pearl City-Waipahu",
	"Nanakuli-Waianae",
	"Castle-Kahuku",
	"Kailua-Kalaheo",
	"Hilo-Waiakea",
	"Kau-Keaau-Pahoa",
	"Honokaa-Kealakehe-Kohala-Konawaena",
	"Baldwin-Kekaulike-Kulanihakoi-Maui",
	"Hana-Lahainaluna-Lanai-Molokai",
	"Kapaa-Kauai-Waimea"
];

const complexes = [
	"Farrington",
	"Kaiser",
	"Kalani",
	"Kaimuki",
	"McKinley",
	"Roosevelt",
	"Aiea",
	"Moanalua",
	"Radford",
	"Leilehua",
	"Mililani",
	"Waialua",
	"Campbell",
	"Kapolei",
	"Pearl City",
	"Waipahu",
	"Nanakuli",
	"Waianae",
	"Castle",
	"Kahuku",
	"Kailua",
	"Kalaheo",
	"Hilo",
	"Waiakea",
	"Kau",
	"Keaau",
	"Pahoa",
	"Honokaa",
	"Kealakehe",
	"Kohala",
	"Konawaena",
	"Baldwin",
	"Kekaulike",
	"Kulanihakoi",
	"Maui",
	"Hana",
	"Lahainaluna",
	"Lanai",
	"Molokai",
	"Kapaa",
	"Kauai",
	"Waimea",
	"Laupahoehoe"
];

export { districts, complexAreas, complexes };
